services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: totalville1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin123"]
      timeout: 20s
      retries: 10
      interval: 3s
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    container_name: python-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: totalville1
      MERCADOPAGO_ACCESS_TOKEN: APP_USR-6969870495921891-062401-609d3e595e1e4ea33274c9f8c251e8d1-656413634 
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://34.95.214.56:5000
      BACKEND_URL_INTERNAL: http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
